import TheHeader from "@/components/TheHeader";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] }); // імпорт та налаштування шрифту

export const metadata: Metadata = {
  // Мета дата яка буде відображатись на сторінці
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <TheHeader />
          <main className="main">
            <div className="container">{children}</div>
          </main>
          <TheFooter />
        </div>
      </body>
    </html>
  );
}
